name: Create second file
on:
  push:
    branches: ["meena"]
  pull_request: 
    branches: ["meena"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: print hello world
      run: echo "Hello World"
    
